---
title: "Econometrics Assignement 7 - Brodard Lionel, Giro Larraz Tomas, Marchal Antoine, Schonenberger Ivan"
output: 
  html_notebook: default
---


------->  Please run this code with ' Run all' of *Ctrl+Alt+R*


# Exercice 2 - Assignement 7
```{r}
# Download the data
df= read.csv('./US_Gasoline_Market.csv')
# Adjust the data-frame
df$CONS=1e6*df$GASEXP/df$GASP/df$POP

#############################################################################################################################################
######################################### (a). Build a model using the simple-to-general approach. ##########################################
#############################################################################################################################################

# Y Vector
Y<-cbind(df$CONS)

# Number of observations
n<-52

# Vector of 1 for the constant
X1<-cbind(replicate(52,1))

# Matrix of X
X_0_SG=cbind(X1)
X_1_SG=cbind(X1,df$INCOME)
X_2_SG=cbind(X1,df$INCOME,df$GASP)
X_3_SG=cbind(X1,df$INCOME,df$GASP,df$PNC)
X_4_SG=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC)
X_5_SG=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT)
X_6_SG=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT)
X_7_SG=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PN)
X_8_SG=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PN,df$PS)
X_9_SG=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PN,df$PS,df$YEAR)


# Number of Regressors
K_SG=rbind(ncol(X_0_SG),ncol(X_1_SG),ncol(X_2_SG),ncol(X_3_SG),ncol(X_4_SG),ncol(X_5_SG),ncol(X_6_SG),ncol(X_7_SG),ncol(X_8_SG),ncol(X_9_SG))

# Estimation of Beta
BetaHat_0_SG=solve(t(X_0_SG)%*%X_0_SG)%*%t(X_0_SG)%*%Y
BetaHat_1_SG=solve(t(X_1_SG)%*%X_1_SG)%*%t(X_1_SG)%*%Y
BetaHat_2_SG=solve(t(X_2_SG)%*%X_2_SG)%*%t(X_2_SG)%*%Y
BetaHat_3_SG=solve(t(X_3_SG)%*%X_3_SG)%*%t(X_3_SG)%*%Y
BetaHat_4_SG=solve(t(X_4_SG)%*%X_4_SG)%*%t(X_4_SG)%*%Y
BetaHat_5_SG=solve(t(X_5_SG)%*%X_5_SG)%*%t(X_5_SG)%*%Y
BetaHat_6_SG=solve(t(X_6_SG)%*%X_6_SG)%*%t(X_6_SG)%*%Y
BetaHat_7_SG=solve(t(X_7_SG)%*%X_7_SG)%*%t(X_7_SG)%*%Y
BetaHat_8_SG=solve(t(X_8_SG)%*%X_8_SG)%*%t(X_8_SG)%*%Y                              
BetaHat_9_SG=solve(t(X_9_SG)%*%X_9_SG)%*%t(X_9_SG)%*%Y

# Matrix M
M_0_SG=diag(n)-X_0_SG%*%solve(t(X_0_SG)%*%X_0_SG)%*%t(X_0_SG)
M_1_SG=diag(n)-X_1_SG%*%solve(t(X_1_SG)%*%X_1_SG)%*%t(X_1_SG)
M_2_SG=diag(n)-X_2_SG%*%solve(t(X_2_SG)%*%X_2_SG)%*%t(X_2_SG)
M_3_SG=diag(n)-X_3_SG%*%solve(t(X_3_SG)%*%X_3_SG)%*%t(X_3_SG)
M_4_SG=diag(n)-X_4_SG%*%solve(t(X_4_SG)%*%X_4_SG)%*%t(X_4_SG)
M_5_SG=diag(n)-X_5_SG%*%solve(t(X_5_SG)%*%X_5_SG)%*%t(X_5_SG)
M_6_SG=diag(n)-X_6_SG%*%solve(t(X_6_SG)%*%X_6_SG)%*%t(X_6_SG)
M_7_SG=diag(n)-X_7_SG%*%solve(t(X_7_SG)%*%X_7_SG)%*%t(X_7_SG)
M_8_SG=diag(n)-X_8_SG%*%solve(t(X_8_SG)%*%X_8_SG)%*%t(X_8_SG)
M_9_SG=diag(n)-X_9_SG%*%solve(t(X_9_SG)%*%X_9_SG)%*%t(X_9_SG)

# Matrix of Error
E_0_SG=M_0_SG%*%Y
E_1_SG=M_1_SG%*%Y
E_2_SG=M_2_SG%*%Y
E_3_SG=M_3_SG%*%Y
E_4_SG=M_4_SG%*%Y
E_5_SG=M_5_SG%*%Y
E_6_SG=M_6_SG%*%Y
E_7_SG=M_7_SG%*%Y
E_8_SG=M_8_SG%*%Y
E_9_SG=M_9_SG%*%Y

# Sum of Squared Errors
EE_0_SG=t(E_0_SG)%*%E_0_SG
EE_1_SG=t(E_1_SG)%*%E_1_SG
EE_2_SG=t(E_2_SG)%*%E_2_SG
EE_3_SG=t(E_3_SG)%*%E_3_SG
EE_4_SG=t(E_4_SG)%*%E_4_SG
EE_5_SG=t(E_5_SG)%*%E_5_SG
EE_6_SG=t(E_6_SG)%*%E_6_SG
EE_7_SG=t(E_7_SG)%*%E_7_SG
EE_8_SG=t(E_8_SG)%*%E_8_SG
EE_9_SG=t(E_9_SG)%*%E_9_SG

# Number of constraints
J_SG<-1

# F-Tests
F_1_SG <- ((EE_0_SG-EE_1_SG)/J_SG)/((EE_1_SG)/(n-K_SG[1,1]))
F_2_SG <- ((EE_1_SG-EE_2_SG)/J_SG)/((EE_2_SG)/(n-K_SG[2,1]))
F_3_SG <- ((EE_2_SG-EE_3_SG)/J_SG)/((EE_3_SG)/(n-K_SG[3,1]))
F_4_SG <- ((EE_3_SG-EE_4_SG)/J_SG)/((EE_4_SG)/(n-K_SG[4,1]))
F_5_SG <- ((EE_4_SG-EE_5_SG)/J_SG)/((EE_5_SG)/(n-K_SG[5,1]))
F_6_SG <- ((EE_5_SG-EE_6_SG)/J_SG)/((EE_6_SG)/(n-K_SG[6,1]))
F_7_SG <- ((EE_6_SG-EE_7_SG)/J_SG)/((EE_7_SG)/(n-K_SG[7,1]))
F_8_SG <- ((EE_7_SG-EE_8_SG)/J_SG)/((EE_8_SG)/(n-K_SG[8,1]))
F_9_SG <- ((EE_8_SG-EE_9_SG)/J_SG)/((EE_9_SG)/(n-K_SG[9,1]))

# Critical F
critical_F_SG<-cbind(replicate(9,1))
  for (i in 1:9){
    critical_F_SG[i,1] <-qf(0.95,J_SG,(n-K_SG[i+1,1]))
  }
# Message
message ("critical F of simple-to-general model")
t(critical_F_SG)
F_SG<-cbind(F_1_SG,F_2_SG,F_3_SG,F_4_SG,F_5_SG,F_6_SG,F_7_SG,F_8_SG,F_9_SG)
message (" F of simple-to-general model")
F_SG
message ("     ")
message ("Variable kept in Simple-to-General Model")
message("INCOME,GASP,PNC,PUC,PPT,PN,PS,YEAR")


```

```{r}

#############################################################################################################################################
######################################### (b). Build a model using the general-to-simple approach. ##########################################
#############################################################################################################################################

# Matrix of X
X_0_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PD,df$PN,df$PS,df$YEAR)
X_1_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PD,df$PN,df$PS,df$YEAR)
X_2_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PD,df$PN,df$PS,df$YEAR)
X_3_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PD,df$PS,df$YEAR)
X_4_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PPT,df$PS,df$YEAR)
X_5_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PUC,df$PS,df$YEAR)
X_6_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PS,df$YEAR)
X_7_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PS,df$YEAR)
X_8_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PS,df$YEAR)
X_9_GS=cbind(X1,df$INCOME,df$GASP,df$PNC,df$PS,df$YEAR)

# Number of Regressors
K_GS=rbind(ncol(X_0_GS),ncol(X_1_GS),ncol(X_2_GS),ncol(X_3_GS),ncol(X_4_GS),ncol(X_5_GS),ncol(X_6_GS),ncol(X_7_GS),ncol(X_8_GS),ncol(X_9_GS))

# Estimation of Beta
BetaHat_0_GS=solve(t(X_0_GS)%*%X_0_GS)%*%t(X_0_GS)%*%Y
BetaHat_1_GS=solve(t(X_1_GS)%*%X_1_GS)%*%t(X_1_GS)%*%Y
BetaHat_2_GS=solve(t(X_2_GS)%*%X_2_GS)%*%t(X_2_GS)%*%Y
BetaHat_3_GS=solve(t(X_3_GS)%*%X_3_GS)%*%t(X_3_GS)%*%Y
BetaHat_4_GS=solve(t(X_4_GS)%*%X_4_GS)%*%t(X_4_GS)%*%Y
BetaHat_5_GS=solve(t(X_5_GS)%*%X_5_GS)%*%t(X_5_GS)%*%Y
BetaHat_6_GS=solve(t(X_6_GS)%*%X_6_GS)%*%t(X_6_GS)%*%Y
BetaHat_7_GS=solve(t(X_7_GS)%*%X_7_GS)%*%t(X_7_GS)%*%Y
BetaHat_8_GS=solve(t(X_8_GS)%*%X_8_GS)%*%t(X_8_GS)%*%Y                              
BetaHat_9_GS=solve(t(X_9_GS)%*%X_9_GS)%*%t(X_9_GS)%*%Y   

# Matrix M
M_0_GS=diag(n)-X_0_GS%*%solve(t(X_0_GS)%*%X_0_GS)%*%t(X_0_GS)
M_1_GS=diag(n)-X_1_GS%*%solve(t(X_1_GS)%*%X_1_GS)%*%t(X_1_GS)
M_2_GS=diag(n)-X_2_GS%*%solve(t(X_2_GS)%*%X_2_GS)%*%t(X_2_GS)
M_3_GS=diag(n)-X_3_GS%*%solve(t(X_3_GS)%*%X_3_GS)%*%t(X_3_GS)
M_4_GS=diag(n)-X_4_GS%*%solve(t(X_4_GS)%*%X_4_GS)%*%t(X_4_GS)
M_5_GS=diag(n)-X_5_GS%*%solve(t(X_5_GS)%*%X_5_GS)%*%t(X_5_GS)
M_6_GS=diag(n)-X_6_GS%*%solve(t(X_6_GS)%*%X_6_GS)%*%t(X_6_GS)
M_7_GS=diag(n)-X_7_GS%*%solve(t(X_7_GS)%*%X_7_GS)%*%t(X_7_GS)
M_8_GS=diag(n)-X_8_GS%*%solve(t(X_8_GS)%*%X_8_GS)%*%t(X_8_GS)
M_9_GS=diag(n)-X_9_GS%*%solve(t(X_9_GS)%*%X_9_GS)%*%t(X_9_GS)

# Matrix of Error
E_0_GS=M_0_GS%*%Y
E_1_GS=M_1_GS%*%Y
E_2_GS=M_2_GS%*%Y
E_3_GS=M_3_GS%*%Y
E_4_GS=M_4_GS%*%Y
E_5_GS=M_5_GS%*%Y
E_6_GS=M_6_GS%*%Y
E_7_GS=M_7_GS%*%Y
E_8_GS=M_8_GS%*%Y
E_9_GS=M_9_GS%*%Y

# Sum of Squared Errors
EE_0_GS=t(E_0_GS)%*%E_0_GS
EE_1_GS=t(E_1_GS)%*%E_1_GS
EE_2_GS=t(E_2_GS)%*%E_2_GS
EE_3_GS=t(E_3_GS)%*%E_3_GS
EE_4_GS=t(E_4_GS)%*%E_4_GS
EE_5_GS=t(E_5_GS)%*%E_5_GS
EE_6_GS=t(E_6_GS)%*%E_6_GS
EE_7_GS=t(E_7_GS)%*%E_7_GS
EE_8_GS=t(E_8_GS)%*%E_8_GS
EE_9_GS=t(E_9_GS)%*%E_9_GS

# Number of constraints
J_GS<-1

# F-Tests
F_0_GS <- ((EE_1_GS-EE_0_GS)/J_GS)/((EE_0_GS)/(n-K_GS[1,1]))
F_1_GS <- ((EE_2_GS-EE_1_GS)/J_GS)/((EE_1_GS)/(n-K_GS[2,1]))
F_2_GS <- ((EE_3_GS-EE_2_GS)/J_GS)/((EE_2_GS)/(n-K_GS[3,1]))
F_3_GS <- ((EE_4_GS-EE_3_GS)/J_GS)/((EE_3_GS)/(n-K_GS[4,1]))
F_4_GS <- ((EE_5_GS-EE_4_GS)/J_GS)/((EE_4_GS)/(n-K_GS[5,1]))
F_5_GS <- ((EE_6_GS-EE_5_GS)/J_GS)/((EE_5_GS)/(n-K_GS[6,1]))
F_6_GS <- ((EE_7_GS-EE_6_GS)/J_GS)/((EE_6_GS)/(n-K_GS[7,1]))
F_7_GS <- ((EE_8_GS-EE_7_GS)/J_GS)/((EE_7_GS)/(n-K_GS[8,1]))
F_8_GS <- ((EE_9_GS-EE_8_GS)/J_GS)/((EE_8_GS)/(n-K_GS[9,1]))

# Critical F
critical_F_GS<-cbind(replicate(9,1))
  for (i in 1:9){
    critical_F_GS[i,1] <-qf(0.95,J_GS,(n-K_GS[i,1]))
  }

# Message
message ("critical F of general-to-simple model")
t(critical_F_GS)
F_GS<-cbind(F_0_GS,F_1_GS,F_2_GS,F_3_GS,F_4_GS,F_5_GS,F_6_GS,F_7_GS,F_8_GS)
message ("F of general-to-simple model")
abs(F_GS)
message ("     ")
message ("Variable kept in General-to-Simple Model")
message("INCOME,GASP,PNC,PS,YEAR")
```

```{r}
#############################################################################################################################################
################## (c) Compare the resulting models using the adjusted R2, the AIC, the BIC, and Vuong???s statistic. Comment #################
#############################################################################################################################################

# Mean of Y
Y_bar <- rep(mean(Y),52)

# Sum of Squared Y deviation around its mean
Y_Y2 <- t((Y-Y_bar))%*%(Y-Y_bar)

# Adjusted R Squared
AdjustedR2_SG<-1-((EE_9_SG)/(n-K_SG[9,1]))/((Y_Y2)/(n-1))
AdjustedR2_GS<-1-((EE_9_GS)/(n-K_SG[9,1]))/((Y_Y2)/(n-1))

# AIC 
AIC_SG<-log(EE_9_SG/n)+2*K_SG[9,1]/n
AIC_GS<-log(EE_9_GS/n)+2*K_GS[9,1]/n

# BIC
BIC_SG<-log(EE_9_SG/n)+K_SG[9,1]*log(n)/n
BIC_GS<-log(EE_9_GS/n)+K_GS[9,1]*log(n)/n

# Vuong Statistics
# Log of Simple-to-General Model
SG_log <- cbind(rep(1,n))
for (i in 1:n){
  SG_log[i,1]<- -0.5*(log(EE_9_SG/n)+((E_9_SG[i,1])^2/(EE_9_SG/n)))
}
# Log of General-to-Simple Model
GS_log <- cbind(rep(1,n))
for (i in 1:n){
  GS_log[i,1]<- -0.5*(log(EE_9_GS/n)+((E_9_GS[i,1])^2/(EE_9_GS/n)))
}
# Difference between the two models
Mi <-(SG_log-GS_log)
# Mean difference between the two models
M_bar <- cbind(rep(mean(Mi),n))
# Vuong Statistics
V=sqrt(n)*((rbind(rep(1,n))%*%Mi/n)/(t((Mi-M_bar))%*%(Mi-M_bar)/n))

message ("Adjusted R2 - Simple-to-General Model")
AdjustedR2_SG
message ("Adjusted R2 - General-to-Simple Model")
AdjustedR2_GS
message ("AIC - Simple-to-General Model")
AIC_SG
message ("AIC - General-to-Simple Model")
AIC_GS
message ("BIC - Simple-to-General Model")
BIC_SG
message ("BIC - General-to-Simple Model")
BIC_GS
message ("Vuong Statistics")
V
```