---
title: "Econometrics Assignement 7 - Brodard Lionel, Giro Larraz Tomas, Marchal Antoine, Schonenberger Ivan"
output: 
  html_notebook: default
---


------->  Please run this code with ' Run all' of *Ctrl+Alt+R*


# Exercice 2 - Assignement 7
```{r}
# Download the data
ndf= read.csv('./US_Gasoline_Market.csv')
# Adjust the data-frame
ndf$CONS=1e6*ndf$GASEXP/ndf$GASP/ndf$POP
ndf$INTERCEPT<-cbind(replicate(52,1))
df <- ndf[,c(13,5,4,6,7,8,9,10,11,1,12,2,3)] 
#############################################################################################################################################
######################################### (a). Build a model using the simple-to-general approach. ##########################################
#############################################################################################################################################
# Y Vector
Y<-cbind(ndf$CONS)
# Mean of Y
Y_bar <- rep(mean(Y),52)
# Sum of Squared Y deviation around its mean
Y_Y2 <- t((Y-Y_bar))%*%(Y-Y_bar)

# Number of observations
n<-52
cols=c(1)
significant = T
while (significant==T) {
  R2_SG<-matrix(nrow=10,ncol=4)
  for (i in (2:10)){
    if ((i %in% cols)==FALSE){
      X<-cbind(df[,c(cols)])
      X<-data.matrix(X)
      M_star<-diag(n)-X%*%solve(t(X)%*%X)%*%t(X)
      E_star<-M_star%*%Y
      EE_star<-t(E_star)%*%E_star
      X_SG<-cbind(X,df[,i])
      X_SG<-data.matrix(X_SG)
      K<-ncol(X)
      M<-diag(n)-X_SG%*%solve(t(X_SG)%*%X_SG)%*%t(X_SG)
      E<-M%*%Y
      EE<-t(E)%*%E
      J<-1
      R2_SG[i,1]=i
      R2_SG[i,2]<-1-((EE)/(n-K))/((Y_Y2)/(n-1))
      R2_SG[i,3]<- ((EE_star-EE)/J)/(EE/(n-K))
      R2_SG[i,4] <-qf(0.95,J,(n-K))
    }
  }
 
 R2_SG<-R2_SG[order(R2_SG[,2],decreasing =T),]
 if (R2_SG[1,3]>R2_SG[1,4]){
   cols=cbind(cols,R2_SG[1,1])
   significant=T
  } else {
   significant=F
  }
}
```

```{r}
#############################################################################################################################################
######################################### (b). Build a model using the general-to-simple approach. ##########################################
#############################################################################################################################################
# Download the data
ndf= read.csv('./US_Gasoline_Market.csv')
# Adjust the data-frame
ndf$CONS=1e6*ndf$GASEXP/ndf$GASP/ndf$POP
ndf$INTERCEPT<-cbind(replicate(52,1))
df <- ndf[,c(13,5,4,6,7,8,9,10,11,1,12,2,3)] 

cols_2=c(1,2,3,4,5,6,7,8,9,10)

significant = T

while (significant==T) {
  R2_GS<-matrix(nrow=10,ncol=4)
  for (i in (2:10)){
    if (i %in% cols_2){
      X<-cbind(df[,c(cols_2)])
      X<-data.matrix(X)
      M<-diag(n)-X%*%solve(t(X)%*%X)%*%t(X)
      E<-M%*%Y
      EE<-t(E)%*%E
      K<-ncol(X)
      X_GS<-X[,-i]
      X_GS<-data.matrix(X_GS)
      M_star<-diag(n)-X_GS%*%solve(t(X_GS)%*%X_GS)%*%t(X_GS)
      E_star<-M_star%*%Y
      EE_star<-t(E_star)%*%E_star
      J<-1
      R2_GS[i,1]=i
      R2_GS[i,2]<- 1-((EE_star)/(n-K))/((Y_Y2)/(n-1))
      R2_GS[i,3]<- ((EE_star-EE)/J)/(EE/(n-K))
      R2_GS[i,4] <-qf(0.95,J,(n-K))
    }
  }
 R2_GS<-R2_GS[order(R2_GS[,2],decreasing =T),]
 if (R2_GS[1,3]<R2_GS[1,4]){
   cols_sort <- cols_2[!cols_2 %in% (R2_GS[1,1])]
   cols_2 <- cols_2[-length(cols_2)]
   significant=T
   df <- df[,cols_sort] 
  } else {
   significant=F
  }
}

```

```{r}
#############################################################################################################################################
################## (c) Compare the resulting models using the adjusted R2, the AIC, the BIC, and Vuong???s statistic. Comment #################
#############################################################################################################################################
# Computation of the important parameters of the Simple-to-General Model
M_SG<-diag(n)-X_SG%*%solve(t(X_SG)%*%X_SG)%*%t(X_SG)
E_SG<-M_SG%*%Y
EE_SG<-t(E_SG)%*%E_SG
K_SG<-ncol(X_SG)

# Computation of the important parameters of the General-to-Simple Model
M_GS<-diag(n)-X_GS%*%solve(t(X_GS)%*%X_GS)%*%t(X_GS)
E_GS<-M_GS%*%Y
EE_GS<-t(E_GS)%*%E_GS
K_GS<-ncol(X_GS)

# Adjusted R Squared
AdjustedR2_SG<-1-((EE_SG)/(n-K_SG))/((Y_Y2)/(n-1))
AdjustedR2_GS<-1-((EE_GS)/(n-K_GS))/((Y_Y2)/(n-1))

# AIC 
AIC_SG<-log(EE_SG/n)+2*K_SG/n
AIC_GS<-log(EE_GS/n)+2*K_GS/n

# BIC
BIC_SG<-log(EE_SG/n)+K_SG*log(n)/n
BIC_GS<-log(EE_GS/n)+K_GS*log(n)/n

# Vuong Statistics
# Log of Simple-to-General Model
SG_log <- cbind(rep(1,n))
for (i in 1:n){
  SG_log[i,1]<- -0.5*(log(EE_SG/n)+((E_SG[i,1])^2/(EE_SG/n)))
}
# Log of General-to-Simple Model
GS_log <- cbind(rep(1,n))
for (i in 1:n){
  GS_log[i,1]<- -0.5*(log(EE_GS/n)+((E_GS[i,1])^2/(EE_GS/n)))
}
# Difference between the two models
Mi <-(SG_log-GS_log)
# Mean difference between the two models
M_bar <- cbind(rep(mean(Mi),n))
# Vuong Statistics
V=sqrt(n)*((rbind(rep(1,n))%*%Mi/n)/(t((Mi-M_bar))%*%(Mi-M_bar)/n))

message ("Adjusted R2 - Simple-to-General Model")
AdjustedR2_SG
message ("Adjusted R2 - General-to-Simple Model")
AdjustedR2_GS
message ("AIC - Simple-to-General Model")
AIC_SG
message ("AIC - General-to-Simple Model")
AIC_GS
message ("BIC - Simple-to-General Model")
BIC_SG
message ("BIC - General-to-Simple Model")
BIC_GS
message ("Vuong Statistics")
V
```