---
title: "Econometrics Assignement 7 - Brodard Lionel, Giro Larraz Tomas, Marchal Antoine, Schonenberger Ivan"
output: 
  html_notebook: default
---


------->  Please run this code with ' Run all' of *Ctrl+Alt+R*

# #######################  Exercice 1 - Assignement 7
# function to calculate the F-statistic
```{r}
fStatistic <- function(R,q,X,b,e){
  J=dim(R)[1]
  K=dim(R)[2]
  n=dim(X)[1]
  return(t(R%*%b-q)%*%solve(R%*%solve(t(X)%*%X)%*%t(R))%*%(R%*%b-q)/J/(t(e)%*%e/(n-K)))
}
```

#Exercise 1

# recalculating the model from as 3.
```{r}
dat <- read.table('./US_Gasoline_Market.csv', header = TRUE, row.names = 1, sep = ",")


## Compute per capita consumption and store data
mat <- as.matrix(dat)
X=cbind(as.matrix(replicate(52,1)),1:52,mat[1:52,3:10])
message('head(X)')
head(X)

Y <- 1000000 * mat[, "GASEXP"] / (mat[, "GASP"] * mat[, "POP"])
Y=as.matrix(Y,ncol=1)
message('head(Y)')
head(Y)
message('b')
b=solve(t(X)%*%X)%*%t(X)%*%Y
b
e=Y-X%*%b
message('head(e)')
head(e)
```


# Entering R and q
```{r}
R=cbind(as.matrix(replicate(9,0)),diag(9))
message('R')
R
q=as.matrix(replicate(9,0))
message('q')
q
```



# Computing the F-statistic using our model
```{r}
library('stats')
fStat=fStatistic(R,q,X,b,e)
message('f-statistic')
fStat
message('\np-value')
1-pf(fStat,9,42)

message('\np-value is less than:')
1-pf(35,9,42)
```

# Computing the F-statistic with an r package
```{r}
model=lm(Y~1+X[1:52,2]+X[1:52,3]+X[1:52,4]+X[1:52,5]+X[1:52,6]+X[1:52,7]+X[1:52,8]+X[1:52,9]+X[1:52,10])
summary(model)
```


# #######################  Exercice 2 - Assignement 7
```{r}
# Download the data
ndf= read.csv('./US_Gasoline_Market.csv')
# Adjust the data-frame
ndf$CONS=1e6*ndf$GASEXP/ndf$GASP/ndf$POP
ndf$INTERCEPT<-cbind(replicate(52,1))
df <- ndf[,c(13,5,4,6,7,8,9,10,11,1,12,2,3)] 
#############################################################################################################################################
######################################### (a). Build a model using the simple-to-general approach. ##########################################
#############################################################################################################################################
# Y Vector
Y<-cbind(ndf$CONS)
# Mean of Y
Y_bar <- rep(mean(Y),52)
# Sum of Squared Y deviation around its mean
Y_Y2 <- t((Y-Y_bar))%*%(Y-Y_bar)


n<-52 # Number of observations
cols=c(1) # vector of kept variables, start with only the intercept
significant = T
while (significant==T) { # While loop to continue add columns to X until the coefficient are not statistically significant
  R2_SG<-matrix(nrow=10,ncol=4) # Matrix of R2 with i, F-test and critical F
  for (i in (2:10)){ # Start at 2, because we keep the intercept in any case
    if ((i %in% cols)==FALSE){ # Test i only if it's not already included in our kept variables
      X<-data.matrix(cbind(df[,c(cols)])) # matrix of X before adding a new column
      M_star<-diag(n)-X%*%solve(t(X)%*%X)%*%t(X)
      E_star<-M_star%*%Y
      EE_star<-t(E_star)%*%E_star
      X<-data.matrix(cbind(X,df[,i])) # matrix of X with a new column i
      K<-ncol(X)
      M<-diag(n)-X%*%solve(t(X)%*%X)%*%t(X)
      E<-M%*%Y
      EE<-t(E)%*%E
      J<-1
      R2_SG[i,1]=i # keep the i
      R2_SG[i,2]<-1-((EE)/(n-K))/((Y_Y2)/(n-1)) # adjusted R2
      R2_SG[i,3]<- ((EE_star-EE)/J)/(EE/(n-K))  # F value
      R2_SG[i,4] <-qf(0.95,J,(n-K)) # critical F
    }
  }
 ##changement below, j'ordonne par F value 
 R2_SG<-R2_SG[order(R2_SG[,3],decreasing =T),] # After building the model with all i, we sort the the R2 matrix by their adjusted R2
 if (R2_SG[1,3]>R2_SG[1,4]){ #If the model with best adjusted R2 has its added column that is satistically significant:
   cols=cbind(cols,R2_SG[1,1]) #we add to our vector of kept variables
   significant=T #so we continue our loop while for a new column to test
  } else {
   significant=F
  }
}
X_SG<-data.matrix(cbind(df[,c(cols)])) # We save our matrix of X for the simple-to-general model for further tests.
```

```{r}
#############################################################################################################################################
######################################### (b). Build a model using the general-to-simple approach. ##########################################
#############################################################################################################################################
# Download the data
ndf= read.csv('./US_Gasoline_Market.csv')
# Adjust the data-frame
ndf$CONS=1e6*ndf$GASEXP/ndf$GASP/ndf$POP
ndf$INTERCEPT<-cbind(replicate(52,1))
df <- ndf[,c(13,5,4,6,7,8,9,10,11,1,12,2,3)] 

cols_2=c(1,2,3,4,5,6,7,8,9,10) # vector of kept variables, start with all the variables

significant = T

while (significant==T) {
  R2_GS<-matrix(nrow=10,ncol=4)
  for (i in (2:10)){
    if (i %in% cols_2){ # Test i only if it's still in our kept variables
      X<-data.matrix(cbind(df[,c(cols_2)])) # Matrix of X without the removed variable
      M<-diag(n)-X%*%solve(t(X)%*%X)%*%t(X)
      E<-M%*%Y
      EE<-t(E)%*%E
      K<-ncol(X)
      X<-data.matrix(X[,-i]) # Matrix of X with the removed variable
      M_star<-diag(n)-X%*%solve(t(X)%*%X)%*%t(X)
      E_star<-M_star%*%Y
      EE_star<-t(E_star)%*%E_star
      J<-1
      R2_GS[i,1]=i # keep i
      R2_GS[i,2]<- 1-((EE_star)/(n-K))/((Y_Y2)/(n-1)) # adjusted R2
      R2_GS[i,3]<- ((EE_star-EE)/J)/(EE/(n-K)) # F value
      R2_GS[i,4] <-qf(0.95,J,(n-K)) # critical F
    }
  }
  ##changement below, j'ordonne par F value 
 R2_GS<-R2_GS[order(R2_GS[,3],decreasing =F),] # After building the model with all i, we sort the the R2 matrix by their adjusted R2
 if (R2_GS[1,3]<R2_GS[1,4]){ #If the model with best adjusted R2 has its added column that is not satistically significant:
   cols_sort <- cols_2[!cols_2 %in% (R2_GS[1,1])] #we remove the variable from our vector of kept variables
   cols_2 <- cols_2[-length(cols_2)] #we readjust the number of variables that we still have
   significant=T #so we continue our loop while for a new column to test
   df <- df[,cols_sort] #we remove from the dataframe the variable we don't need
  } else {
   significant=F
  }
}
X_GS<-data.matrix(cbind(df[,c(cols_2)])) # We save our matrix of X for the general-to-simple model for further tests.

```

```{r}
#############################################################################################################################################
################## (c) Compare the resulting models using the adjusted R2, the AIC, the BIC, and Vuong???s statistic. Comment #################
#############################################################################################################################################
# Computation of the important parameters of the Simple-to-General Model
M_SG<-diag(n)-X_SG%*%solve(t(X_SG)%*%X_SG)%*%t(X_SG)
E_SG<-round(M_SG%*%Y,3)
EE_SG<-t(E_SG)%*%E_SG
K_SG<-ncol(X_SG)
Beta_SG<-solve(t(X_SG)%*%X_SG)%*%t(X_SG)%*%Y

# Computation of the important parameters of the General-to-Simple Model
M_GS<-diag(n)-X_GS%*%solve(t(X_GS)%*%X_GS)%*%t(X_GS)
E_GS<-round(M_GS%*%Y,3)
EE_GS<-t(E_GS)%*%E_GS
K_GS<-ncol(X_GS)
Beta_GS<-solve(t(X_GS)%*%X_GS)%*%t(X_GS)%*%Y

# Adjusted R Squared
AdjustedR2_SG<-1-((EE_SG)/(n-K_SG))/((Y_Y2)/(n-1))
AdjustedR2_GS<-1-((EE_GS)/(n-K_GS))/((Y_Y2)/(n-1))

# AIC 
AIC_SG<-log(EE_SG/n)+2*K_SG/n
AIC_GS<-log(EE_GS/n)+2*K_GS/n

# BIC
BIC_SG<-log(EE_SG/n)+K_SG*log(n)/n
BIC_GS<-log(EE_GS/n)+K_GS*log(n)/n

# Vuong Statistics
# Log of Simple-to-General Model
SG_log <- cbind(rep(1,n))
for (i in 1:n){
  SG_log[i,1]<- -0.5*(log(EE_SG/n)+((E_SG[i,1])^2/(EE_SG/n)))
}
# Log of General-to-Simple Model
GS_log <- cbind(rep(1,n))
for (i in 1:n){
  GS_log[i,1]<- -0.5*(log(EE_GS/n)+((E_GS[i,1])^2/(EE_GS/n)))
}
# Difference between the two models
Mi <-(SG_log-GS_log)
Sum_Mi_n<- 1/n*(rbind(rep(1,n)))%*%Mi
# Mean difference between the two models
M_bar <- cbind(rep(mean(Mi),n))
# Vuong Statistics
V=sqrt(n)*(Sum_Mi_n/sqrt((t((Mi-M_bar))%*%(Mi-M_bar)/n)))

message ("Adjusted R2 - Simple-to-General Model")
AdjustedR2_SG
message ("Adjusted R2 - General-to-Simple Model")
AdjustedR2_GS
message ("AIC - Simple-to-General Model")
AIC_SG
message ("AIC - General-to-Simple Model")
AIC_GS
message ("BIC - Simple-to-General Model")
BIC_SG
message ("BIC - General-to-Simple Model")
BIC_GS
message ("Vuong Statistics")
V
```
# #######################  Exercice 3 - Assignement 7
```{r}
install.packages("ggm")
library(ggm)

df <- read.csv('./US_Gasoline_Market.csv')

##Build y
CONS<-1e6*df$GASEXP/(df$GASP*df$POP)
y <- CONS

##Build design matrix X
##Add intercept
df <- df[,c("INCOME","GASP","PNC","PUC","PPT","PD","PN","PS","YEAR")]
df <- cbind(rep(1,nrow(df)),df)
n <- nrow(df)

##get all subset of possible columns
ps <- powerset(2:ncol(df))
perms<- vector("list", length(ps))

##don't forget to test model with only intercept
perms[[1]]<- c()
for(i in 2:(length(ps)+1)){
  perms[[i]]<-c(unlist(ps[i-1]))
}

getBeta <-function(y,X){
  solve(t(X)%*%X)%*%t(X)%*%y
}

rmses <- c()
for(p in perms){
  res <- c()
  for(i in 1:n){
    design_X <- data.matrix(df[-i,c(1,p)])
    design_y <- y[-i]
    beta <- getBeta(design_y,design_X)
    pred_err <- ((y[i]-data.matrix(df[i,c(1,p)])%*%beta)**2)/n
    res <- append(res,pred_err)
  }
  rmses <- append(rmses, sqrt(sum(res)))
}


table <- cbind(1:length(perms),rmses)
##full model,
full_model_rmse <-table[nrow(table),2]

table <- table[order(table[,2], decreasing = F),]

##Best and worst models rmse and columns
##to get columns input for i do perms[[best[i,1]]] and get a list of numbers
## and get the corresponding variables
best <- table[1:5,]
worst <- table[(nrow(table)-5):nrow(table),]

##simple to general,
##As seen on exercise 3 doing simple to general we keep columns
##INTERCEPT YEAR PS INCOME and GASP, which correspond to the
##236th permutation. We find it on the table
SG_rmse <- table[9,2]
```
