---
title: "Econometrics Assignement 10- Brodard Lionel, Giro Tomas, Marchal Antoine, Schonenberger Ivan"
output: 
  html_notebook: default
---


------->  Please run this code with ' Run all' of *Ctrl+Alt+R*


# Exercise 3
# Question b)
```{r}
n<-10000
set.seed(100)# for reproductibility
X1<-cbind(rnorm(n,mean=0,sd=1))
set.seed(456)
X2<-cbind(rnorm(n,mean=0,sd=1))
Y<-X1/X2
Ym_mean<-c(rep_len(0,n))
Yi<-Y[1]
Ym_mean[1]<-Y[1]
for(i in 2:n){
  Yi<-Yi+Y[i]
  Ym_mean[i]<-Yi/i
  
}

plot(Ym_mean,type="l",main="Mean of Cauchy distributed variables",xlab="number of variables (m)")

```
#question c)
#standard normal 
```{r}
set.seed(123)
Y<-cbind(rnorm(n,mean=0,sd=1))

Ym_mean<-c(rep_len(0,n))
Yi<-Y[1]
Ym_mean[1]<-Y[1]
for(i in 2:n){
  Yi<-Yi+Y[i]
  Ym_mean[i]<-Yi/i
  
}

plot(Ym_mean,type="l",main="Mean of standarly normally distributed variables",xlab="number of variables (m)")
```
#Student
```{r}
set.seed(123)
Y<-cbind(rt(n,df=3))
Ym_mean<-c(rep_len(0,n))
Yi<-Y[1]
Ym_mean[1]<-Y[1]
for(i in 2:n){
  Yi<-Yi+Y[i]
  Ym_mean[i]<-Yi/i
  
}

plot(Ym_mean,type="l",main="Mean of variables distributed as student (dof=3) ",xlab="number of variables (m)")
```

