---
title: "Econometrics Assignement 9- Brodard Lionel, Giro Tomas, Marchal Antoine, Schonenberger Ivan"
output: 
  html_notebook: default
---


------->  Please run this code with ' Run all' of *Ctrl+Alt+R*


# Exercise 2
# Question b) Generate the data
```{r}
## Parameters
beta_0 <- 0.5
beta_1 <- 0.8
beta_2 <- 1.3
beta <-rbind(beta_0,beta_1,beta_2)

R <- 1000 # number of samples
n <- 2000 # number of observations by sample
K<-3 #number of variables


## Creation of the Matrices of the variables, the error terms and calculation of Ys from 1000 different samples of size 2000


betahat<-c()#will be matrix of dim 3 x R
betaIV<-c() #fore)
betaIVf<-c()#for f)
Var<-c() #estimators of assymptotic variance of betaIV put in vector of dim R
Varf<-c()
for (i in 1:R){
U <- cbind(rnorm(n,mean=0,sd=1))
V <- cbind(rnorm(n,mean=0,sd=1))
W <- cbind(rnorm(n,mean=0,sd=1))
X0_i <- cbind(rep_len(1,n))
X1_i <- cbind(U+W)
X2_i <- rt(n,8)
X_i<-cbind(X0_i,X1_i,X2_i)
eps_i <- cbind(U+V)
Y_i <- X_i%*%beta+ eps_i #generation of the ith sample
betahat_i<-solve(t(X_i)%*%X_i)%*%t(X_i)%*%Y_i #beta estimator of the ith sample
eta<-cbind(rnorm(n,mean=0,sd=1))
Z1_i<-cbind(sqrt(0.7)*W+sqrt(0.3)*eta)#for e)
Z_i<-cbind(X0_i,Z1_i,X2_i)#X0 and X1 are not endogenous and can be used as instrumental variables and we have K=L
Z2_i<-cbind(sqrt(0.2)*W+sqrt(0.8)*eta)#for f)
Z_if<-cbind(X0_i,Z2_i,X2_i)
betaIVi<-solve(t(Z_i)%*%X_i)%*%t(Z_i)%*%Y_i #for K=L
betaIVif<-solve(t(Z_if)%*%X_i)%*%t(Z_if)%*%Y_i
e_i<-Y_i-X_i%*%betaIVi
e_if<-Y_i-X_i%*%betaIVif
sigma2_i<-(t(e_i)%*%e_i)/n# estimator of the variance sigma squarred
sigma2_if<-(t(e_if)%*%e_if)/n 
Var_i<-c()
Var_if<-c()
for (j in 1:K){
S<-(solve(t(Z_i)%*%X_i)%*%t(Z_i)%*%Z_i%*%solve(t(X_i)%*%Z_i))
Var_i[j]<-S[j,j]*sigma2_i #select the diagonal value 
Sf<-(solve(t(Z_if)%*%X_i)%*%t(Z_if)%*%Z_if%*%solve(t(X_i)%*%Z_if))
Var_if[j]<-Sf[j,j]*sigma2_if
}


betahat<-cbind(betahat,betahat_i)
betaIV<-cbind(betaIV,betaIVi)
Var<-cbind(Var,Var_i)
betaIVf<-cbind(betaIVf,betaIVif)
Varf<-cbind(Varf,Var_if)

}

#average of beta_k
betahat0<-betahat[1,]
betahat1<-betahat[2,]
betahat2<-betahat[3,]
meanbetahat<-rbind(mean(betahat0),mean(betahat1),mean(betahat2))
meanbetahat<-rbind(mean(betahat0),mean(betahat1),mean(betahat2))
message("Real Betas:")
beta
message("Average OLS estimation:")
round(meanbetahat,3)
```

#Question2.c)

```{r}
#generation of a sample of size N2=1000
N2=1000
U <- cbind(rnorm(N2,mean=0,sd=1))
V <- cbind(rnorm(N2,mean=0,sd=1))
W <- cbind(rnorm(N2,mean=0,sd=1))
X0_new <- cbind(rep_len(1,N2))
X1_new <- cbind(U+W)
X2_new <- rt(N2,8)
X_new<-cbind(X0_new,X1_new,X2_new)
eps_new <- cbind(U+V)
Y_new <- X_new%*%beta+ eps_new
#for question c)
eta_new <- cbind(rnorm(N2,mean=0,sd=1))
Z1_new<-cbind(sqrt(0.7)*W+sqrt(0.3)*eta_new)
Z_new<-cbind(X0_new,Z1_new,X2_new) #X0 and X1 are not endogenous and can be used as instrumental variables and we have K=L


################################taking 100 subsamples of size n2=100
N<-100
n2<-100
betahat100<-c() #will be matrix of dim 3 x 100 that contains estimator for the 100 different samples
#for question d)
betaIV100<-c()
for (i in 1:N){
  
  selection<-sample( seq(1,N2),n2) #random vector that contains n2 elements of the sequence 1:1000
  Y_newi<-Y_new[selection]#select 100 elements among the 1000 elements
  X0_newi<-X0_new[selection]
  X1_newi<-X1_new[selection]
  X2_newi<-X2_new[selection]
  Z1_newi<-Z1_new[selection] 
  Z_newi<-cbind(X0_newi,Z1_newi,X2_newi)
  X_newi<-cbind(X0_newi,X1_newi,X2_newi)
  betahat100i<-solve(t(X_newi)%*%X_newi)%*%t(X_newi)%*%Y_newi
  betaIV100i<-solve(t(Z_newi)%*%X_newi)%*%t(Z_newi)%*%Y_newi
  betahat100<-cbind(betahat100, betahat100i)
  betaIV100<-cbind(betaIV100,betaIV100i)
}
#average of beta_k (n2=100)
betahat0100<-betahat100[1,]
betahat1100<-betahat100[2,]
betahat2100<-betahat100[3,]
meanbetahat100<-rbind(mean(betahat0100),mean(betahat1100),mean(betahat2100))

################################taking 100 subsamples of size n2=200
n2<-200
betahat200<-c() #will be matrix of dim 3 x 100 that contains estimator for the 100 different samples
#for question c)
betaIV200<-c()
for (i in 1:N){
  
  selection<-sample( seq(1,N2),n2) #random vector that contains n2 elements of the sequence 1:1000
  Y_newi<-Y_new[selection] #select 200 elements among the 1000 elements
  X0_newi<-X0_new[selection]
  X1_newi<-X1_new[selection]
  X2_newi<-X2_new[selection]
  Z1_newi<-Z1_new[selection] #for d)
  Z_newi<-cbind(X0_newi,Z1_newi,X2_newi)
  X_newi<-cbind(X0_newi,X1_newi,X2_newi)
  betahat200i<-solve(t(X_newi)%*%X_newi)%*%t(X_newi)%*%Y_newi
  betaIV200i<-solve(t(Z_newi)%*%X_newi)%*%t(Z_newi)%*%Y_newi
  betahat200<-cbind(betahat200, betahat200i)
  betaIV200<-cbind(betaIV200,betaIV200i)
}
#average of beta_k (n2=200)
betahat0200<-betahat200[1,]
betahat1200<-betahat200[2,]
betahat2200<-betahat200[3,]
meanbetahat200<-rbind(mean(betahat0200),mean(betahat1200),mean(betahat2200))

################################taking 100 subsamples of size n2=500
n2<-500
betahat500<-c() #will be matrix of dim 3 x 100 that contains estimator for the 100 different samples
#for question d)
betaIV500<-c()
for (i in 1:N){
  
  selection<-sample( seq(1,N2),n2) #random vector that contains n2 elements of the sequence 1:1000
  Y_newi<-Y_new[selection] #select 500 elements among the 1000 elements
  X0_newi<-X0_new[selection]
  X1_newi<-X1_new[selection]
  X2_newi<-X2_new[selection]
  Z1_newi<-Z1_new[selection] #for d)
  Z_newi<-cbind(X0_newi,Z1_newi,X2_newi)
  X_newi<-cbind(X0_newi,X1_newi,X2_newi)
  betahat500i<-solve(t(X_newi)%*%X_newi)%*%t(X_newi)%*%Y_newi
  betaIV500i<-solve(t(Z_newi)%*%X_newi)%*%t(Z_newi)%*%Y_newi
  betahat500<-cbind(betahat500, betahat500i)
  betaIV500<-cbind(betaIV500,betaIV500i)
}
#average of beta_k (n2=500)
betahat0500<-betahat500[1,]
betahat1500<-betahat500[2,]
betahat2500<-betahat500[3,]
meanbetahat500<-rbind(mean(betahat0500),mean(betahat1500),mean(betahat2500))

################################taking 100 subsamples of size n2=750
n2<-750
betahat750<-c() #will be matrix of dim 3 x 100 that contains estimator for the 100 different samples
#for question d)
betaIV750<-c()
for (i in 1:N){
  
  selection<-sample( seq(1,N2),n2) #random vector that contains n2 elements of the sequence 1:1000
  Y_newi<-Y_new[selection] #select 750 elements among the 1000 elements
  X0_newi<-X0_new[selection]
  X1_newi<-X1_new[selection]
  X2_newi<-X2_new[selection]
  Z1_newi<-Z1_new[selection] #for d)
  Z_newi<-cbind(X0_newi,Z1_newi,X2_newi)
  X_newi<-cbind(X0_newi,X1_newi,X2_newi)
  betahat750i<-solve(t(X_newi)%*%X_newi)%*%t(X_newi)%*%Y_newi
  betaIV750i<-solve(t(Z_newi)%*%X_newi)%*%t(Z_newi)%*%Y_newi
  betahat750<-cbind(betahat750, betahat750i)
  betaIV750<-cbind(betaIV750,betaIV750i)
}
#average of beta_k (n2=750)
betahat0750<-betahat750[1,]
betahat1750<-betahat750[2,]
betahat2750<-betahat750[3,]
meanbetahat750<-rbind(mean(betahat0750),mean(betahat1750),mean(betahat2750))
################################Entire sample

betahat_new<-solve(t(X_new)%*%X_new)%*%t(X_new)%*%Y_new
meanbetahat_total<-cbind(meanbetahat100,meanbetahat200,meanbetahat500,meanbetahat750,betahat_new)
message("Average OLS estimation by subsample:")
round(meanbetahat_total,3)


```
#Question2.d)
```{r}
#we have K=L, therefore betaIV is given by: betaIV<-solve(t(Z)%*%X)%*%t(Z)%*%Y (implemented in part c))
#n2=100
betaIV0100<-betaIV100[1,]
betaIV1100<-betaIV100[2,]
betaIV2100<-betaIV100[3,]
meanbetaIV100<-rbind(mean(betaIV0100),mean(betaIV1100),mean(betaIV2100))
#n2=200
betaIV0200<-betaIV200[1,]
betaIV1200<-betaIV200[2,]
betaIV2200<-betaIV200[3,]
meanbetaIV200<-rbind(mean(betaIV0200),mean(betaIV1200),mean(betaIV2200))
#n2=500
betaIV0500<-betaIV500[1,]
betaIV1500<-betaIV500[2,]
betaIV2500<-betaIV500[3,]
meanbetaIV500<-rbind(mean(betaIV0500),mean(betaIV1500),mean(betaIV2500))
#n2=750
betaIV0750<-betaIV750[1,]
betaIV1750<-betaIV750[2,]
betaIV2750<-betaIV750[3,]
meanbetaIV750<-rbind(mean(betaIV0750),mean(betaIV1750),mean(betaIV2750))
#all sample
betaIV_new<-solve(t(Z_new)%*%X_new)%*%t(Z_new)%*%Y_new

meanbetahat_IV<-cbind(meanbetaIV100,meanbetaIV200,meanbetaIV500,meanbetaIV750,betaIV_new)
message("IV estimation by subsample:")
round(meanbetahat_IV,3)
```
#Question2.e)
```{r}
t<-qt(0.975,n) #  for alpha=0.05
I0<-cbind(rep_len(0,R),rep_len(0,R)) #the first column will contain the inferior bound the other the superior bound of the interval
I1<-cbind(rep_len(0,R),rep_len(0,R)) #for the estimator of the second parameter
I2<-cbind(rep_len(0,R),rep_len(0,R)) #confidence interval for the third estimator
I0[,1]<-cbind(betaIV[1,]-t*sqrt(Var[1,]))
I0[,2]<-cbind(betaIV[1,]+t*sqrt(Var[1,]))
I1[,1]<-cbind(betaIV[2,]-t*sqrt(Var[2,]))
I1[,2]<-cbind(betaIV[2,]+t*sqrt(Var[2,]))
I2[,1]<-cbind(betaIV[3,]-t*sqrt(Var[3,]))
I2[,2]<-cbind(betaIV[3,]+t*sqrt(Var[3,]))
C0<-0#will keep track of the number of times beta0 is covered by the interval
C1<-0
C2<-0
for(i in 1:R){
  if(beta_0>I0[i,1] & beta_0<I0[i,2]){C0=C0+1}
  if(beta_1>I1[i,1] & beta_1<I1[i,2]){C1=C1+1}
  if(beta_2>I2[i,1] & beta_2<I2[i,2]){C2=C2+1}
  }
message('the empirical coverage probabilities of the R confidence intervals for beta_0 is')
print(C0/R)
message('the empirical coverage probabilities of the R confidence intervals for beta_1 is')
print(C1/R)
message('the empirical coverage probabilities of the R confidence intervals for beta_2 is')
print(C2/R)

```
#Question2.f)
```{r}
I0f<-cbind(rep_len(0,R),rep_len(0,R)) #the first column will contain the inferior bound the other the superior bound of the interval
I1f<-cbind(rep_len(0,R),rep_len(0,R)) #for the estimator of the second parameter
I2f<-cbind(rep_len(0,R),rep_len(0,R))
I0f[,1]<-cbind(betaIVf[1,]-t*sqrt(Varf[1,]))
I0f[,2]<-cbind(betaIVf[1,]+t*sqrt(Varf[1,]))
I1f[,1]<-cbind(betaIVf[2,]-t*sqrt(Varf[2,]))
I1f[,2]<-cbind(betaIVf[2,]+t*sqrt(Varf[2,]))
I2f[,1]<-cbind(betaIVf[3,]-t*sqrt(Varf[3,]))
I2f[,2]<-cbind(betaIVf[3,]+t*sqrt(Varf[3,]))
C0f<-0#will keep track of the number of times beta0 is covered by the interval
C1f<-0
C2f<-0
for(i in 1:R){
  if(beta_0>I0f[i,1] & beta_0<I0f[i,2]){C0f=C0f+1}
  if(beta_1>I1f[i,1] & beta_1<I1f[i,2]){C1f=C1f+1}
  if(beta_2>I2f[i,1] & beta_2<I2f[i,2]){C2f=C2f+1}
  }
message('the empirical coverage probabilities of the R confidence intervals for beta_0 is')
print(C0f/R)
message('the empirical coverage probabilities of the R confidence intervals for beta_1 is')
print(C1f/R)
message('the empirical coverage probabilities of the R confidence intervals for beta_2 is')
print(C2f/R)

```
