---
title: "Econometrics Assignement 9- Brodard Lionel, Giro Tomas, Marchal Antoine, Schonenberger Ivan"
output: 
  html_notebook: default
---


------->  Please run this code with ' Run all' of *Ctrl+Alt+R*


# Exercise 2
# Question b) Generate the data
```{r}
## Parameters
beta_0 <- 0.5
beta_1 <- 0.8
beta_2 <- 1.3
beta <-rbind(beta_0,beta_1,beta_2)

R <- 1000 # number of samples
n <- 2000 # number of observations by sample
n1 <- 2000 # number of observations by sample

## Creation of the Matrix of X, the error term and calculation of Y

U <- cbind(rnorm(n,mean=0,sd=1))
V <- cbind(rnorm(n,mean=0,sd=1))
W <- cbind(rnorm(n,mean=0,sd=1))
eta <- cbind(rnorm(n,mean=0,sd=1))
X0 <- cbind(rep_len(1,n))
X1 <- cbind(U+W)
X2 <- rt(n,8)
X<-cbind(X0,X1,X2)
eps <- cbind(U+V)

Y <- X%*%beta+ eps

## Creation of the estimated parameters
hatbeta_0<-replicate(R,1) # We create a hatAlphas list
hatbeta_1<-replicate(R,1)
hatbeta_2<-replicate(R,1)
for (i in 1:R){
  sample_i=sample(1:R,n1, replace = TRUE)
  sample_i
  X_i=X[sample_i,1:3]
  Y_i=Y[sample_i,1]
  X_i
  Y_i
  OLSestimators=solve(t(X_i)%*%X_i)%*%t(X_i)%*%Y_i
  hatbeta_0[i]=OLSestimators[1]
  hatbeta_1[i]=OLSestimators[2]
  hatbeta_2[i]=OLSestimators[3]
}
hatbeta<-cbind(hatbeta_0,hatbeta_1,hatbeta_2)
meanhatbeta<-rbind(mean(hatbeta_0),mean(hatbeta_1),mean(hatbeta_2))
message('Betas=')
beta
message('Avg Beta Hat=')
round(meanhatbeta,3)
```

```{r}
l<-5
New_hatbeta_0<-replicate(l,1) # We create a hatAlphas list
New_hatbeta_1<-replicate(l,1)
New_hatbeta_2<-replicate(l,1)
n2<-cbind(100,200,500,750,1000)
m2<-100
for (j in 1:l){
  sample_j=sample(n2[j],m2, replace = TRUE)
  X_j=X[sample_j,1:3]
  Y_j=Y[sample_j,1]
  X_j
  Y_j
  OLSestimators=solve(t(X_j)%*%X_j)%*%t(X_j)%*%Y_j
  New_hatbeta_0[j]=OLSestimators[1]
  New_hatbeta_1[j]=OLSestimators[2]
  New_hatbeta_2[j]=OLSestimators[3]
}

New_hatbeta<-rbind(New_hatbeta_0,New_hatbeta_1,New_hatbeta_2)
message('New Beta Hat=')
New_hatbeta

```

