---
title: "Econometrics AS3"
output: html_notebook
---
# Exercise 4
```{r}
X1=rnorm(1000,mean=0, sd= 4)
eps=matrix(rnorm(1000,mean=0,sd=1/2),c(1000,1))
Y=0.5*matrix(replicate(1000,1),c(1000,1))+1.4*X1+eps
X=cbind(replicate(1000,1),X1)

message('head(X)=')
head(X)

message('\nhead(Y)=')
head(Y)

message('\nhead(eps)=')
head(eps)

hatAlphas=replicate(1000,1) # We create a hatAlphas list
hatBetas=replicate(1000,1)

for (i in 1:1000){
  sample_i=sample(1:1000,100, replace = TRUE)
  sample_i
  X_i=X[sample_i,1:2]
  Y_i=Y[sample_i,1]
  X_i
  Y_i
  OLSestimators=solve(t(X_i)%*%X_i)%*%t(X_i)%*%Y_i
  hatAlphas[i]=OLSestimators[1]
  hatBetas[i]=OLSestimators[2]
}

message('\nhead(hatAlphas)=')
head(hatAlphas)

message('\nhead(hatBetas)=')
head(hatBetas)

hist(hatAlphas,
     main = 'Histogram of the estimates of alpha',
     xlab = 'alpha hat')
hist(hatBetas,
     main = 'Histogram of the estimates of beta',
     xlab='beta hat')



```

We can see that the two plots are centered around the real values of alpha and beta. This is because the ols estimators are unbiased.

# Exercise 5: U.S. gasoline market
```{r}
df= read.csv('./US_Gasoline_Market.csv')
head(df)


CONS=1e6*df$GASEXP/df$GASP/df$POP
df$CONS=CONS


png(filename="./ex5-1-1.png", units="in", width=5, height=8, res=300)
par(mfrow=c(3,1))

plot(df$YEAR,
     df$CONS,
     main='Plot of the consumption as a function\n of the year',
     ylab='Consumption per capita',
     xlab='year')
plot(df$GASEXP,
     df$CONS,
     main = 'Plot of the consumption as a function\n of total U.S gas expenditure',
     ylab='Consumption per capita',
     xlab='total U.S. gas expenditure')
plot(df$POP,
     df$CONS,
     main='Plot of the consumption as a function\n of total U.S. population',
     ylab='Consumption per capita',
     xlab='total U.S. population')

dev.off()

png(filename="./ex5-1-2.png", units="in", width=5, height=8, res=300)
par(mfrow=c(3,1))

plot(df$GASP,
     df$CONS,
     main = 'Plot of the consumption per capita as a function\n of the price index of gasoline' ,
     ylab='Consumption per capita',
     xlab='price index of gasoline')
plot(df$INCOME,
     df$CONS,
     main = 'Plot of the consumption per capita as a function\n of per capita disposable income',
     ylab='Consumption per capita',
     xlab='per capita disposable income')
plot(df$PNC,
     df$CONS,
     main = 'Plot of the consumption per capita as a function\n of the price index of new cars',
     ylab='Consumption per capita',
     xlab='price index of new cars')
dev.off()

png(filename="./ex5-1-3.png", units="in", width=5, height=8, res=300)
par(mfrow=c(3,1))
plot(df$PUC,
     df$CONS,
     main= 'Plot of the consumption per capita as a function\n of the price index of used cars',
     ylab='Consumption per capita',
     xlab='price index of used cars')
plot(df$PPT,
     df$CONS,
     main='Plot of the consumptions per capita as a function\n of the price index for public transportation',
     ylab='Consumption per capita',
     xlab='price index for public transportation')
plot(df$PD,
     df$CONS,
     main='Plot of the consumption per capita as a function\n of agregate price index for consumer durables',
     ylab='Consumption per capita',
     xlab='agregate price for consumer durables')
dev.off()

png(filename="./ex5-1-4.png", units="in", width=5, height=8, res=300)
par(mfrow=c(3,1))
plot(df$PN,
     df$CONS,
     main='Plot of the consumption per capita as a function\n of agregate price index for consumer nondurables',
     ylab='Consumption per capita',
     xlab='agregate price index for consumer nondurables')
plot(df$PS,
     df$CONS,
     main='Plot of the consumption per capita as a function\n of agregate price index for consumer services',
     ylab='Consumption per capita',
     xlab='agregate price index for consumer services')
dev.off()


```